/*-----------------------------------------------------------------------------+
 | This file is generated by NReact.Csx. Do not modify, changes could be lost. |
 +-----------------------------------------------------------------------------*/
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;

#if NETFX_CORE
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Media;
#else
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
#endif

using NReact;

public partial class NDemo 
{
  public override NElement Render()
  {
    return 
      New(typeof(StackPanel), new { VerticalAlignment = "Center", HorizontalAlignment = "Center" }, 
        New(typeof(NClock), new { FS =  Props.FontSize  }), 
        New(typeof(Button), new { Click =  (RoutedEventHandler)ClickMe , Content = "Click me" + ((int)Props.FontSize), HorizontalAlignment = "Center", Foreground = "Red" }), 
        New(typeof(NClock), new { FS =  60.0 - Props.FontSize  })
      );
  }
}
